language: minimal

services:
  - docker

script:
  - docker --version
  - docker-compose -f docker-compose-build.yaml build --parallel

deploy:
  provider: script
  script: bash docker-push.sh
  on:
    branch: master
